final countries = {
  'Afghanistan': {'country_code': 'AF', 'dial_code': 93},
  'Albania': {'country_code': 'AL', 'dial_code': 355},
  'Algeria': {'country_code': 'DZ', 'dial_code': 213},
  'Andorra': {'country_code': 'AD', 'dial_code': 376},
  'Angola': {'country_code': 'AO', 'dial_code': 244},
  'Argentina': {'country_code': 'AR', 'dial_code': 54},
  'Armenia': {'country_code': 'AM', 'dial_code': 374},
  'Aruba': {'country_code': 'AW', 'dial_code': 297},
  'Australia': {'country_code': 'AU', 'dial_code': 61},
  'Austria': {'country_code': 'AT', 'dial_code': 43},
  'Azerbaijan': {'country_code': 'AZ', 'dial_code': 994},
  'Bahrain': {'country_code': 'BH', 'dial_code': 973},
  'Bangladesh': {'country_code': 'BD', 'dial_code': 880},
  'Belgium': {'country_code': 'BE', 'dial_code': 32},
  'Belize': {'country_code': 'BZ', 'dial_code': 501},
  'Benin': {'country_code': 'BJ', 'dial_code': 229},
  'Bhutan': {'country_code': 'BT', 'dial_code': 975},
  'Bolivia, Plurinational State of': {'country_code': 'BO', 'dial_code': 591},
  'Bonaire, Sint Eustatius and Saba': {'country_code': 'BQ', 'dial_code': 599},
  'Bosnia and Herzegovina': {'country_code': 'BA', 'dial_code': 387},
  'Botswana': {'country_code': 'BW', 'dial_code': 267},
  'Brazil': {'country_code': 'BR', 'dial_code': 55},
  'British Indian Ocean Territory': {'country_code': 'IO', 'dial_code': 246},
  'Brunei Darussalam': {'country_code': 'BN', 'dial_code': 673},
  'Bulgaria': {'country_code': 'BG', 'dial_code': 359},
  'Burkina Faso': {'country_code': 'BF', 'dial_code': 226},
  'Burundi': {'country_code': 'BI', 'dial_code': 257},
  'Cabo Verde': {'country_code': 'CV', 'dial_code': 238},
  'Cambodia': {'country_code': 'KH', 'dial_code': 855},
  'Cameroon': {'country_code': 'CM', 'dial_code': 237},
  'Canada': {'country_code': 'CA', 'dial_code': 1},
  'Cayman Islands': {'country_code': 'KY', 'dial_code': 1},
  'Central African Republic': {'country_code': 'CF', 'dial_code': 236},
  'Chad': {'country_code': 'TD', 'dial_code': 235},
  'Chile': {'country_code': 'CL', 'dial_code': 56},
  'Christmas Island': {'country_code': 'CX', 'dial_code': 61},
  'Cocos (Keeling) Islands': {'country_code': 'CC', 'dial_code': 61},
  'Colombia': {'country_code': 'CO', 'dial_code': 57},
  'Comoros': {'country_code': 'KM', 'dial_code': 269},
  'Congo': {'country_code': 'CG', 'dial_code': 242},
  'Congo, The Democratic Republic of the': {
    'country_code': 'CD',
    'dial_code': 243
  },
  'Cook Islands': {'country_code': 'CK', 'dial_code': 682},
  'Costa Rica': {'country_code': 'CR', 'dial_code': 506},
  'Croatia': {'country_code': 'HR', 'dial_code': 385},
  'Cuba': {'country_code': 'CU', 'dial_code': 53},
  'Curaçao': {'country_code': 'CW', 'dial_code': 599},
  'Cyprus': {'country_code': 'CY', 'dial_code': 357},
  'Czechia': {'country_code': 'CZ', 'dial_code': 420},
  "Côte d'Ivoire": {'country_code': 'CI', 'dial_code': 225},
  'Denmark': {'country_code': 'DK', 'dial_code': 45},
  'Djibouti': {'country_code': 'DJ', 'dial_code': 253},
  'Dominica': {'country_code': 'DM', 'dial_code': 1},
  'Dominican Republic': {'country_code': 'DO', 'dial_code': 1},
  'Ecuador': {'country_code': 'EC', 'dial_code': 593},
  'Egypt': {'country_code': 'EG', 'dial_code': 20},
  'El Salvador': {'country_code': 'SV', 'dial_code': 503},
  'Equatorial Guinea': {'country_code': 'GQ', 'dial_code': 240},
  'Eritrea': {'country_code': 'ER', 'dial_code': 291},
  'Estonia': {'country_code': 'EE', 'dial_code': 372},
  'Eswatini': {'country_code': 'SZ', 'dial_code': 268},
  'Ethiopia': {'country_code': 'ET', 'dial_code': 251},
  'Falkland Islands (Malvinas)': {'country_code': 'FK', 'dial_code': 500},
  'Faroe Islands': {'country_code': 'FO', 'dial_code': 298},
  'Fiji': {'country_code': 'FJ', 'dial_code': 679},
  'Finland': {'country_code': 'FI', 'dial_code': 358},
  'France': {'country_code': 'FR', 'dial_code': 33},
  'French Guiana': {'country_code': 'GF', 'dial_code': 594},
  'French Polynesia': {'country_code': 'PF', 'dial_code': 689},
  'French Southern Territories': {'country_code': 'TF', 'dial_code': 0},
  'Gabon': {'country_code': 'GA', 'dial_code': 241},
  'Gambia': {'country_code': 'GM', 'dial_code': 220},
  'Georgia': {'country_code': 'GE', 'dial_code': 995},
  'Germany': {'country_code': 'DE', 'dial_code': 49},
  'Ghana': {'country_code': 'GH', 'dial_code': 233},
  'Gibraltar': {'country_code': 'GI', 'dial_code': 350},
  'Greece': {'country_code': 'GR', 'dial_code': 30},
  'Greenland': {'country_code': 'GL', 'dial_code': 299},
  'Grenada': {'country_code': 'GD', 'dial_code': 1},
  'Guadeloupe': {'country_code': 'GP', 'dial_code': 590},
  'Guam': {'country_code': 'GU', 'dial_code': 1},
  'Guatemala': {'country_code': 'GT', 'dial_code': 502},
  'Guernsey': {'country_code': 'GG', 'dial_code': 44},
  'Guinea': {'country_code': 'GN', 'dial_code': 224},
  'Guinea-Bissau': {'country_code': 'GW', 'dial_code': 245},
  'Guyana': {'country_code': 'GY', 'dial_code': 592},
  'Haiti': {'country_code': 'HT', 'dial_code': 509},
  'Heard Island and McDonald Islands': {'country_code': 'HM', 'dial_code': 0},
  'Holy See (Vatican City State)': {'country_code': 'VA', 'dial_code': 39},
  'Honduras': {'country_code': 'HN', 'dial_code': 504},
  'Hong Kong': {'country_code': 'HK', 'dial_code': 852},
  'Hungary': {'country_code': 'HU', 'dial_code': 36},
  'Iceland': {'country_code': 'IS', 'dial_code': 354},
  'India': {'country_code': 'IN', 'dial_code': 91},
  'Indonesia': {'country_code': 'ID', 'dial_code': 62},
  'Iran, Islamic Republic of': {'country_code': 'IR', 'dial_code': 98},
  'Iraq': {'country_code': 'IQ', 'dial_code': 964},
  'Ireland': {'country_code': 'IE', 'dial_code': 353},
  'Isle of Man': {'country_code': 'IM', 'dial_code': 44},
  'Israel': {'country_code': 'IL', 'dial_code': 972},
  'Italy': {'country_code': 'IT', 'dial_code': 39},
  'Jamaica': {'country_code': 'JM', 'dial_code': 1},
  'Japan': {'country_code': 'JP', 'dial_code': 81},
  'Jersey': {'country_code': 'JE', 'dial_code': 44},
  'Jordan': {'country_code': 'JO', 'dial_code': 962},
  'Kazakhstan': {'country_code': 'KZ', 'dial_code': 7},
  'Kenya': {'country_code': 'KE', 'dial_code': 254},
  'Kiribati': {'country_code': 'KI', 'dial_code': 686},
  'Korea': {'country_code': 'KR', 'dial_code': 82},
  'Kuwait': {'country_code': 'KW', 'dial_code': 965},
  'Kyrgyzstan': {'country_code': 'KG', 'dial_code': 996},
  "Lao People's Democratic Republic": {'country_code': 'LA', 'dial_code': 856},
  'Latvia': {'country_code': 'LV', 'dial_code': 371},
  'Lebanon': {'country_code': 'LB', 'dial_code': 961},
  'Lesotho': {'country_code': 'LS', 'dial_code': 266},
  'Liberia': {'country_code': 'LR', 'dial_code': 231},
  'Libya': {'country_code': 'LY', 'dial_code': 218},
  'Liechtenstein': {'country_code': 'LI', 'dial_code': 423},
  'Lithuania': {'country_code': 'LT', 'dial_code': 370},
  'Luxembourg': {'country_code': 'LU', 'dial_code': 352},
  'Macao': {'country_code': 'MO', 'dial_code': 853},
  'Madagascar': {'country_code': 'MG', 'dial_code': 261},
  'Malawi': {'country_code': 'MW', 'dial_code': 265},
  'Malaysia': {'country_code': 'MY', 'dial_code': 60},
  'Maldives': {'country_code': 'MV', 'dial_code': 960},
  'Mali': {'country_code': 'ML', 'dial_code': 223},
  'Malta': {'country_code': 'MT', 'dial_code': 356},
  'Marshall Islands': {'country_code': 'MH', 'dial_code': 692},
  'Martinique': {'country_code': 'MQ', 'dial_code': 596},
  'Mauritania': {'country_code': 'MR', 'dial_code': 222},
  'Mauritius': {'country_code': 'MU', 'dial_code': 230},
  'Mayotte': {'country_code': 'YT', 'dial_code': 262},
  'Mexico': {'country_code': 'MX', 'dial_code': 52},
  'Micronesia, Federated States of': {'country_code': 'FM', 'dial_code': 691},
  'Moldova, Republic of': {'country_code': 'MD', 'dial_code': 373},
  'Monaco': {'country_code': 'MC', 'dial_code': 377},
  'Mongolia': {'country_code': 'MN', 'dial_code': 976},
  'Montenegro': {'country_code': 'ME', 'dial_code': 382},
  'Montserrat': {'country_code': 'MS', 'dial_code': 1},
  'Morocco': {'country_code': 'MA', 'dial_code': 212},
  'Mozambique': {'country_code': 'MZ', 'dial_code': 258},
  'Myanmar': {'country_code': 'MM', 'dial_code': 95},
  'Namibia': {'country_code': 'NA', 'dial_code': 264},
  'Nauru': {'country_code': 'NR', 'dial_code': 674},
  'Nepal': {'country_code': 'NP', 'dial_code': 977},
  'Netherlands': {'country_code': 'NL', 'dial_code': 31},
  'New Caledonia': {'country_code': 'NC', 'dial_code': 687},
  'New Zealand': {'country_code': 'NZ', 'dial_code': 64},
  'Nicaragua': {'country_code': 'NI', 'dial_code': 505},
  'Niger': {'country_code': 'NE', 'dial_code': 227},
  'Nigeria': {'country_code': 'NG', 'dial_code': 234},
  'Niue': {'country_code': 'NU', 'dial_code': 683},
  'Norfolk Island': {'country_code': 'NF', 'dial_code': 672},
  'North Macedonia': {'country_code': 'MK', 'dial_code': 389},
  'Northern Mariana Islands': {'country_code': 'MP', 'dial_code': 1},
  'Norway': {'country_code': 'NO', 'dial_code': 47},
  'Oman': {'country_code': 'OM', 'dial_code': 968},
  'Palau': {'country_code': 'PW', 'dial_code': 680},
  'Palestine, State of': {'country_code': 'PS', 'dial_code': 970},
  'Panama': {'country_code': 'PA', 'dial_code': 507},
  'Papua New Guinea': {'country_code': 'PG', 'dial_code': 675},
  'Paraguay': {'country_code': 'PY', 'dial_code': 595},
  'Peru': {'country_code': 'PE', 'dial_code': 51},
  'Philippines': {'country_code': 'PH', 'dial_code': 63},
  'Poland': {'country_code': 'PL', 'dial_code': 48},
  'Portugal': {'country_code': 'PT', 'dial_code': 351},
  'Puerto Rico': {'country_code': 'PR', 'dial_code': 1},
  'Qatar': {'country_code': 'QA', 'dial_code': 974},
  'Romania': {'country_code': 'RO', 'dial_code': 40},
  'Rwanda': {'country_code': 'RW', 'dial_code': 250},
  'Réunion': {'country_code': 'RE', 'dial_code': 262},
  'Saint Barthélemy': {'country_code': 'BL', 'dial_code': 590},
  'Saint Helena, Ascension and Tristan da Cunha': {
    'country_code': 'SH',
    'dial_code': 290
  },
  'Saint Kitts and Nevis': {'country_code': 'KN', 'dial_code': 1},
  'Saint Lucia': {'country_code': 'LC', 'dial_code': 1},
  'Saint Martin (French part)': {'country_code': 'MF', 'dial_code': 590},
  'Saint Pierre and Miquelon': {'country_code': 'PM', 'dial_code': 508},
  'Saint Vincent and the Grenadines': {'country_code': 'VC', 'dial_code': 1},
  'Samoa': {'country_code': 'WS', 'dial_code': 685},
  'San Marino': {'country_code': 'SM', 'dial_code': 378},
  'Sao Tome and Principe': {'country_code': 'ST', 'dial_code': 239},
  'Saudi Arabia': {'country_code': 'SA', 'dial_code': 966},
  'Senegal': {'country_code': 'SN', 'dial_code': 221},
  'Serbia': {'country_code': 'RS', 'dial_code': 381},
  'Seychelles': {'country_code': 'SC', 'dial_code': 248},
  'Sierra Leone': {'country_code': 'SL', 'dial_code': 232},
  'Singapore': {'country_code': 'SG', 'dial_code': 65},
  'Sint Maarten (Dutch part)': {'country_code': 'SX', 'dial_code': 1},
  'Slovakia': {'country_code': 'SK', 'dial_code': 421},
  'Slovenia': {'country_code': 'SI', 'dial_code': 386},
  'Solomon Islands': {'country_code': 'SB', 'dial_code': 677},
  'Somalia': {'country_code': 'SO', 'dial_code': 252},
  'South Africa': {'country_code': 'ZA', 'dial_code': 27},
  'South Georgia and the South Sandwich Islands': {
    'country_code': 'GS',
    'dial_code': 0
  },
  'South Sudan': {'country_code': 'SS', 'dial_code': 211},
  'Spain': {'country_code': 'ES', 'dial_code': 34},
  'Sri Lanka': {'country_code': 'LK', 'dial_code': 94},
  'Sudan': {'country_code': 'SD', 'dial_code': 249},
  'Suriname': {'country_code': 'SR', 'dial_code': 597},
  'Svalbard and Jan Mayen': {'country_code': 'SJ', 'dial_code': 47},
  'Sweden': {'country_code': 'SE', 'dial_code': 46},
  'Switzerland': {'country_code': 'CH', 'dial_code': 41},
  'Taiwan, Province of China': {'country_code': 'TW', 'dial_code': 886},
  'Tajikistan': {'country_code': 'TJ', 'dial_code': 992},
  'Tanzania, United Republic of': {'country_code': 'TZ', 'dial_code': 255},
  'Thailand': {'country_code': 'TH', 'dial_code': 66},
  'Timor-Leste': {'country_code': 'TL', 'dial_code': 670},
  'Togo': {'country_code': 'TG', 'dial_code': 228},
  'Tokelau': {'country_code': 'TK', 'dial_code': 690},
  'Tonga': {'country_code': 'TO', 'dial_code': 676},
  'Trinidad and Tobago': {'country_code': 'TT', 'dial_code': 1},
  'Tunisia': {'country_code': 'TN', 'dial_code': 216},
  'Turkey': {'country_code': 'TR', 'dial_code': 90},
  'Turkmenistan': {'country_code': 'TM', 'dial_code': 993},
  'Turks and Caicos Islands': {'country_code': 'TC', 'dial_code': 1},
  'Tuvalu': {'country_code': 'TV', 'dial_code': 688},
  'Uganda': {'country_code': 'UG', 'dial_code': 256},
  'Ukraine': {'country_code': 'UA', 'dial_code': 380},
  'United Arab Emirates': {'country_code': 'AE', 'dial_code': 971},
  'United Kingdom': {'country_code': 'GB', 'dial_code': 44},
  'United States': {'country_code': 'US', 'dial_code': 1},
  'Uruguay': {'country_code': 'UY', 'dial_code': 598},
  'Uzbekistan': {'country_code': 'UZ', 'dial_code': 998},
  'Vanuatu': {'country_code': 'VU', 'dial_code': 678},
  'Venezuela, Bolivarian Republic of': {'country_code': 'VE', 'dial_code': 58},
  'Vietnam': {'country_code': 'VN', 'dial_code': 84},
  'Wallis and Futuna': {'country_code': 'WF', 'dial_code': 681},
  'Western Sahara': {'country_code': 'EH', 'dial_code': 212},
  'Yemen': {'country_code': 'YE', 'dial_code': 967},
  'Zambia': {'country_code': 'ZM', 'dial_code': 260},
  'Zimbabwe': {'country_code': 'ZW', 'dial_code': 263},
};
